- menu_name: "Informazioni utili"

- name: "Prenota un colloquio"
  url: "/contact/"
  title: "Contatti"

- name: "Come lavoro"
  url: "/come-lavoro/"
  title: "Metodo di lavoro"

- name: "Domande frequenti"
  url: "/faq/"
  title: "FAQ"

- name: "Aree di intervento"
  url: "/aree-intervento/"
  title: "Aree di intervento"
